# Generated by Django 4.2.7 on 2023-11-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('FolderID', models.IntegerField(primary_key=True, serialize=False)),
                ('Folder_Name', models.CharField(max_length=255, unique=True)),
                ('Created_At', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Google_UserID', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Access_Token', models.CharField(max_length=255)),
                ('Refresh_Token', models.CharField(max_length=255)),
                ('Created_At', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('RepositoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('Repository_Name', models.CharField(max_length=255, unique=True)),
                ('Url', models.TextField()),
                ('FolderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.folders')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('HistoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('Timestap', models.DateTimeField()),
                ('FolderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.folders')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.users')),
            ],
        ),
        migrations.AddField(
            model_name='folders',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.users'),
        ),
    ]
