# Generated by Django 4.2.5 on 2023-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='FolderID',
        ),
        migrations.AlterField(
            model_name='folders',
            name='FolderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='HistoryID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='RepositoryID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
