# Generated by Django 4.2.5 on 2023-11-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_history_userid_alter_folders_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='Folder_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.folders'),
        ),
    ]
