# Generated by Django 4.2.5 on 2023-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_repository_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='Repository_Name',
            field=models.CharField(max_length=255),
        ),
    ]
