# Generated by Django 4.2.7 on 2024-01-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_repository_repository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='Repository_Name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
